export const mockInterpreterRate = {
    id: 'rate_123',
    interpreterId: 'interp_456',
    certifiedHourlyRate: '55.00',
    qualifiedHourlyRate: '30.00',
    minimumHours: '2.00',
    mileageRate: '0.67',
    acceptsNoMileage: false,
    certifiedLateCancelFee: '120.00',
    qualifiedLateCancelFee: '80.00',
    certifiedNoShowFee: '120.00',
    qualifiedNoShowFee: '80.00',
    effectiveDate: new Date('2026-01-01'),
    endDate: null,
    notes: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
  
  export const mockAppointment = (overrides = {}) => ({
    id: 'appt_001',
    bookingId: 'BK-2026-0001',
    date: new Date('2026-01-15'),
    status: 'Completed',
    interpreterId: 'interp_456',
    language: 'Spanish',
    isCertified: true,
    actualDurationMinutes: 120,
    actualMiles: '25',
    mileageApproved: true,
    projectedDuration: '2.00',
    patientFirstName: 'John',
    patientLastName: 'Doe',
    facilityName: 'Memorial Hospital',
    payoutStatus: 'pending',
    ...overrides,
  })